title: Juan Arriagada
email: jarrcan@gmail.com
description: >-
  I’m a Software Engineer, Cybersecurity Specialist, and AI Enthusiast with 
  over a decade of experience designing and developing innovative software 
  solutions. I lead digital transformation projects, combining technical 
  expertise with strategic thinking to enhance systems' scalability, security, 
  and usability.

baseurl: ""
url: "https://jarriagadac.github.io"

twitter_username: jarrcan
github_username:  jarriagadac

plugins:
  - jekyll-feed
  - jekyll-multiple-languages-plugin

languages: ["es", "en"]
exclude_from_localizations: ["assets"]
